#!/usr/bin/env node
/**
 * Regenerates `CONTENT.md` — the human-readable version of the site's content
 * plan — from `src/_data/sidebar.js`.
 *
 * The sidebar is the single source of truth for site structure, so this is a
 * projection of it rather than a second thing to keep in sync.
 *
 *   node scripts/print-outline.js
 */

import {existsSync} from 'node:fs';
import {writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import sidebar from '../src/_data/sidebar.js';

const SRC = fileURLToPath(new URL('../src/', import.meta.url));
const OUT = fileURLToPath(new URL('../CONTENT.md', import.meta.url));

const SECTION_TITLES = {'/guide/': 'Guide', '/reference/': 'Reference'};

/** Mirrors the path mapping in scaffold-docs.js. */
const sourcePathFor = (link, allLinks) => {
  const isDirectory = allLinks.some((l) => l !== link && l.startsWith(link));
  const segments = link.split('/').filter(Boolean);
  return isDirectory
    ? join(...segments, 'index.md')
    : join(...segments.slice(0, -1), `${segments.at(-1)}.md`);
};

const collectLinks = (items) =>
  items.flatMap((item) => [
    ...(item.link ? [item.link] : []),
    ...collectLinks(item.items ?? []),
  ]);

/** A page counts as written once it no longer carries the Draft badge. */
const isDraft = async (path) => {
  const full = join(SRC, path);
  if (!existsSync(full)) return true;
  const {readFile} = await import('node:fs/promises');
  return (await readFile(full, 'utf8')).includes('status: Draft');
};

const lines = [
  '# Zena docs — content outline',
  '',
  '<!-- Generated by scripts/print-outline.js. Edit src/_data/sidebar.js. -->',
  '',
  'This is the plan for the documentation site. The sidebar configuration in',
  '[`src/_data/sidebar.js`](src/_data/sidebar.js) is the source of truth: it',
  "defines the navigation, the page order, and — via each leaf's `outline` —",
  'the sections a page is meant to cover.',
  '',
  'To add a page: add it to the sidebar with an `outline`, then run',
  '`node scripts/scaffold-docs.js` to create the stub.',
  '',
  '**Status:** ✅ written · 📝 placeholder',
  '',
];

let written = 0;
let total = 0;

for (const [prefix, tree] of Object.entries(sidebar)) {
  lines.push(`## ${SECTION_TITLES[prefix] ?? prefix}`, '');
  const links = collectLinks(tree);

  const walk = async (items, depth) => {
    for (const item of items) {
      const indent = '  '.repeat(depth);

      if (!item.link) {
        lines.push(`${indent}- **${item.text}**`);
      } else {
        total++;
        const path = sourcePathFor(item.link, links);
        const draft = await isDraft(path);
        if (!draft) written++;
        lines.push(
          `${indent}- ${draft ? '📝' : '✅'} [${item.text}](src/${path}) — \`${item.link}\``,
        );
        for (const heading of item.outline ?? []) {
          lines.push(`${indent}  - ${heading}`);
        }
      }

      if (item.items) await walk(item.items, depth + 1);
    }
  };

  await walk(tree, 0);
  lines.push('');
}

lines.push(
  '---',
  '',
  `${written} of ${total} pages written; ${total - written} still placeholders.`,
  '',
);

await writeFile(OUT, lines.join('\n'));
console.log(`wrote CONTENT.md — ${written}/${total} pages written`);
