[workspace]
members = [
    "packages/zena-runtime",
    "packages/zena-run",
    "packages/zena-cli",
    "packages/zenafx",
]
resolver = "2"

[workspace.dependencies]
wasmtime = { version = "48.0.0", features = ["cache"] }
wasmtime-wasi = "48.0.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.44", features = ["full"] }
winit = { version = "0.30" }
env_logger = "0.11"
log = "0.4"
wasi-webgpu-wasmtime = { git = "https://github.com/wasi-gfx/wasi-gfx-runtime" }
surface-wasmtime = { git = "https://github.com/wasi-gfx/wasi-gfx-runtime", features = ["winit", "surface-webgpu", "surface-frame-buffer"] }
frame-buffer-wasmtime = { git = "https://github.com/wasi-gfx/wasi-gfx-runtime" }
